set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 10

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#24273a fg=#cad3f5'
set -g mouse on

bind r source-file ~/.tmux.conf
set -g base-index 1
set -g renumber-windows on

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Split panes 
bind v split-window -h
bind s split-window -v 

# Unbind the default split mappings
unbind '"'
unbind %

# Remove kill pane confirmation prompt
unbind x
bind x kill-pane

# Close tmux session
bind Q kill-session
